app.py
"app.py -- flask entry-point"

import flask
from lib import core_blueprint
from lib.util import ssl_middleware

APP = flask.Flask(__name__)
APP.before_request(ssl_middleware)
APP.register_blueprint(core_blueprint.CORE)

lib/core_blueprint.py
"core_blueprint.py -- flask Blueprint for core functionality"

import binascii, json, os
from dataclasses import dataclass
import flask, scrypt
from Crypto.Cipher import AES
from Crypto.Util import Padding
from marshmallow import Schema, fields, validate, ValidationError
from .util import init_pool, insert_stmt, strip_empty, withcon
from . import diff_summary, search

CORE = flask.Blueprint('core', __name__)
STATES = json.load(open(os.path.join(os.path.split(__file__)[0], 'states.json')))['states']
GLOBAL_SALT = binascii.unhexlify(os.environ['ARB_SALT'])
ARB_CRYPT = binascii.unhexlify(os.environ['ARB_CRYPT'])

@CORE.context_processor
def inject_version():
  return {'version': os.environ.get('VERSION')}

# todo: would rather this happened at app startup vs registration i.e. import.
# But before_first_request is too late.
CORE.record(init_pool)

@CORE.route('/')
def splash():
  return flask.render_template('splash.jinja.htm')

@dataclass
class CatPair:
  key: str
  label: str

CATEGORIES = [
  CatPair('nadvert', 'Not as advertised'),
  CatPair('ndeliv', 'Never delivered'),
  CatPair('nwork', "Doesn't work"),
  CatPair('price', "Overcharged, undercharged, or bad price"),
  CatPair('navail', 'Outage or intermittent availability'),
  CatPair('ncompat', 'Not compatible with other stuff'),
  CatPair('mistreat', 'Mistreatment by company'),
  CatPair('woreout', 'Wore out quickly'),
  CatPair('danger', 'Dangerous or caused an injury'),
  CatPair('late', 'Arrived late'),
  CatPair('npay', 'Underpaid or paid late'),
  CatPair('other', 'Other'),
]
CAT_LOOKUP = {pair.key: pair.label for pair in CATEGORIES}

AFFIRMATION = """I affirm, on penalty of perjury, that I believe my submission to be (1) accurate and (2) not a duplicate submission.

I understand that submitting information to this database could expose me to legal risks."""

@CORE.route('/submit')
def get_submit():
  return flask.render_template('submit.jinja.htm', categories=CATEGORIES, affirmation=AFFIRMATION, states=STATES)

def yesno(required=False):
  return fields.Str(validate=validate.OneOf(['yes', 'no']), required=required)

class SubmissionSchema(Schema):
  counterparty = fields.Str()
  counterparty_domain = fields.Str()
  claimant = yesno(True)
  issue_cat = fields.Str(validate=validate.OneOf([cat.key for cat in CATEGORIES]), required=True)
  issue_det = fields.Str()
  terms_link = fields.Str()
  you_negotiate = yesno()
  sought_dollars = fields.Int()
  settlement_dollars = fields.Int()
  favor = yesno()
  fair = yesno()
  incident_date = fields.DateTime(format='%Y-%m')
  dispute_date = fields.DateTime(format='%Y-%m')
  file_date = fields.DateTime(format='%Y-%m')
  arb_date = fields.DateTime(format='%Y-%m', required=True)
  agency = fields.Str()
  state = fields.Str(validate=validate.OneOf([row[0] for row in STATES]), required=True)
  chose = fields.Str(validate=validate.OneOf(['yes', 'yes_list', 'no']))
  case_real_id = fields.Str()
  email = fields.Email()
  password = fields.Str()
  affirm = fields.Str(required=True)

  @staticmethod
  def valid_affirm(value):
    if value.replace('\r\n', '\n') != AFFIRMATION:
      raise ValidationError('invalid affirmation')

@CORE.errorhandler(ValidationError)
def handle_validation_error(err):
  return flask.render_template('invalid.jinja.htm', messages=err.messages)

def yesno_null(value):
  "cast non-null yesno to bool"
  # todo: do this with marshmallow
  return {'yes': True, 'no': False, None: None}[value]

def date_null(value):
  return value and value.date()

@CORE.route('/submit', methods=['POST'])
def post_submit():
  # ValidationError here gets caught by middleware
  parsed = SubmissionSchema().load(strip_empty(flask.request.form))
  db_fields = {
    'counterparty': parsed.get('counterparty'),
    'counterparty_domain': parsed.get('counterparty_domain'),
    'submitter_initiated': yesno_null(parsed.get('claimant')),
    'issue_category': parsed.get('issue_cat'),
    'issue': parsed.get('issue_det'),
    'terms_link': parsed.get('terms_link'),
    'draft_contract': yesno_null(parsed.get('you_negotiate')),
    'sought_dollars': parsed.get('sought_dollars'),
    'settlement_dollars': parsed.get('settlement_dollars'),
    'subjective_inmyfavor': yesno_null(parsed.get('favor')),
    'subjective_fair': yesno_null(parsed.get('fair')),
    'incident_date': date_null(parsed.get('incident_date')),
    'dispute_date': date_null(parsed.get('dispute_date')),
    'file_date': date_null(parsed.get('file_date')),
    'arbitration_date': date_null(parsed.get('arb_date')),
    'arbitration_agency': parsed.get('agency'),
    # todo: agency domain
    'arbitration_state': parsed.get('state'),
    'submitter_choose_agency': parsed.get('chose'),
    'affirm': parsed.get('affirm'),
  }
  if 'email' in parsed:
    block_size = 16
    ivec = os.urandom(block_size)
    db_fields['email_iv'] = ivec
    padded = Padding.pad(parsed['email'].encode('utf8'), block_size)
    db_fields['email_cipher'] = AES.new(ARB_CRYPT, AES.MODE_CBC, ivec).encrypt(padded)
  if 'case_real_id' in parsed:
    db_fields['real_id_hash'] = scrypt.hash(parsed['case_real_id'], GLOBAL_SALT)
  if 'password' in parsed:
    salt = os.urandom(12)
    db_fields['password_salt'] = salt
    db_fields['password_hash'] = scrypt.hash(parsed['password'], salt)
  with withcon() as con, con.cursor() as cur:
    cur.execute(insert_stmt('cases', 'caseid', db_fields), db_fields)
    con.commit()
  return flask.render_template('after_submit.jinja.htm')

@CORE.route('/search')
def get_search():
  return flask.render_template('search.jinja.htm', categories=CATEGORIES, states=STATES)

@CORE.route('/search', methods=['POST'])
def post_search():
  # todo: look into marshmallow-dataclass so we're not relying on psycopg2 / libpq for sanitization
  params = search.Search(**strip_empty(flask.request.form))
  if params.empty():
    return 'Error: set at least one search term'
  rows = search.search(params)
  groups = diff_summary.diff_group_counterparty(rows)
  summaries = [diff_summary.summarize(key, rows) for key, rows in groups.items()]
  # note: sorting by party key so stable sort doesn't reveal relative sizes
  summaries.sort(key=lambda summary: (summary.total, summary.key))
  # todo: paging
  summaries = summaries[:20]
  for summary in summaries:
    for approx in summary.issue_cats:
      approx.label = CAT_LOOKUP.get(approx.label, approx.label)
    for approx in summary.settlement_dollars:
      approx.label = f"${approx.label.lower} - ${approx.label.upper}"
  return flask.render_template('serp.jinja.htm', summaries=summaries)

@CORE.route('/disputes')
def disputes():
  return flask.render_template('dispute.jinja.htm')

@CORE.route('/terms')
def terms():
  return flask.render_template('terms.jinja.htm')

@CORE.route('/health')
def get_health():
  return flask.jsonify({"ok": True})

class IntentionalCrash(Exception):
  "intentional crash to test error reporting"

@CORE.route('/crash')
def get_crash():
  raise IntentionalCrash

templates/after_submit.jinja.htm
{% from 'macros.jinja.htm' import home_link %}
{% extends "base.jinja.htm" %}
{% block title %}submission received{% endblock %}
{% block container %}
{{ home_link() }}
<h1>Submission received</h1>
<p>Information about index inclusion</p>
<p>Todo: edit link if you posted a password</p>
{% endblock container %}

templates/base.jinja.htm
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title>⚖️ Arbout - {% block title %}{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{{url_for('static', filename='bootstrap.min.css')}}">
</head>
<body>
<div class="container">
{% block container %}{% endblock %}
<p><a href="{{url_for('core.terms')}}">Terms and privacy</a></p>
{% if version %}<p>Server version {{version}}</p>{% endif %}
</div>
</body>
</html>

templates/dispute.jinja.htm
{% from 'macros.jinja.htm' import home_link %}
{% extends "base.jinja.htm" %}
{% block title %}disputes{% endblock %}
{% block container %}
{{ home_link() }}
<h1>Disputes</h1>
<p>If you believe the information in this database to be in error, please <a href="mailto:awinter.public+arboutdispute@gmail.com">email the maintainer</a>.</p>
<h3>Standard dispute process</h3>
<p>If you believe that our database contains false or mis-reported cases:</p>
<ul>
  <li>If you are an arbitration agency, you may share your entire list of cases along with an affidavit that the list is complete and correct.</li>
  <li>If you are a party to arbitration, you must additionally share affidavits from each arbitration agency in the list.</li>
</ul>
<p>We will hold your case list in strict confidence and, as long as we believe it to be correct, we will only use it to remove false information from our site.</p>
<p>If we discover your list to be substantially in error, we may restore the cases we removed because of it. We may pursue legal action for fraud or other harms. If a court grants us relief, we may publish the list.</p>
<hr>
<h3>Preemptive disputes</h3>
<p>If you're an agency or a party to many arbitrations and you want to pre-upload your case list for dispute matching, contact us. Our technology doesn't currently support this but we're open to building the extension once we have a partner.</p>
<hr>
{% endblock container %}

templates/invalid.jinja.htm
{% extends "base.jinja.htm" %}
{% block title %}validation error{% endblock %}
{% block container %}
<h1>🛑 Validation error</h1>
<h2>Something was wrong with your request</h2>
<p>The following fields had problems:</p>
<table class="table">
  {% for field, errs in messages.items() %}
  <tr>
    <td>{{field}}<td>
    <td>{{', '.join(errs)}}<td>
  </tr>
  {% endfor %}
</table>
{% endblock container %}

templates/macros.jinja.htm
{% macro yesno(name, options=[('yes', "Yes"), ('no', "No")], required=False) %}
  {% for value, label in options %}
    <br>
    <label><input type="radio" name="{{name}}" value={{value}} {{'required' if required}}> {{label}}</label>
  {% endfor %}
{% endmacro %}

{% macro option_warn() %}
  <div class="alert alert-warning"><b>Warning</b>: this is optional and could expose you to extra risk if the counterparty thinks you violated confidentiality</div>
{% endmacro %}

{% macro home_link() %}
<div class="clearfix"><div class="float-right"><a href="{{url_for('core.splash')}}">⚖️ Arbout</a></div></div>
{% endmacro %}

{% macro select_state(states, include_none=False) %}
<select class="form-control" name="state">
  {% if include_none %}<option value="">---</option>{% endif %}
  {% for short, long in states %}<option value="{{short}}">{{short}} - {{long}}</option>{% endfor %}
</select>
{% endmacro %}

{% macro select_issue_cat(categories, include_none=False, required=False) %}
<select class="form-control" name="issue_cat" {{'required' if required}}>
  {% if include_none %}<option value="">---</option>{% endif %}
  {% for cat in categories %}<option value="{{cat.key}}">{{cat.label}}</option>{% endfor %}
</select>
{% endmacro %}

templates/search.jinja.htm
{% from 'macros.jinja.htm' import home_link, select_state, select_issue_cat %}
{% extends "base.jinja.htm" %}
{% block title %}search{% endblock %}
{% block container %}
{{ home_link() }}
<h1>🔎 Search cases</h1>
<br>
<form method="POST">
  <div class="form-group"><label>
    Party name
    <input name="party" class="form-control" type="text" placeholder="Party">
  </label></div>
  <div class="form-group"><label>
    Party website
    <input name="party_domain" class="form-control" type="text" placeholder="Party domain">
  </label></div>
  <div class="form-group"><label>
    Start / end year
    <input name="start_year" class="form-control" type="number" placeholder="Start year">
    <input name="end_year" class="form-control" type="number" placeholder="End year">
  </label></div>
  <div class="form-group"><label>
    Arbitration state
    <p class="text-muted">State where the arbitration took place</p>
    {{select_state(states, include_none=True)}}
  </label></div>
  <button role="submit" class="btn btn-primary">🔎 Search</button>
  <hr>
</form>
{% endblock container %}

templates/serp.jinja.htm
{% from 'macros.jinja.htm' import home_link %}
{% extends "base.jinja.htm" %}
{% block title %}search results{% endblock %}
{% block container %}
{{ home_link() }}
{% macro label_rows(root, rows) %}
  {% for row in rows %}
  <tr><td>{{root}}: {{row.label}}</td><td>{{row.bracket.render()}}</td></tr>
  {% endfor %}
{% endmacro %}
<h1>🔎 Search results</h1>
<p class="text-muted">Note: this version of the software only shows the first 20 results of a search</p>
{% if not summaries %}
  <div class="alert alert-warning">Empty! Either there were no results or there weren't enough results to summarize</div>
{% else %}
  {% for summary in summaries %}
  <div class="card"><details class="card-body" open>
    <summary class="h4 card-title">Party: {{summary.key.value}}</summary>
    <table class="table">
      <tr><td>Total cases</td> <td>{{summary.total.render()}}</td></tr>
      {{ label_rows('Agency', summary.agencies) }}
      {{ label_rows('Issue', summary.issue_cats) }}
      {{ label_rows('Year', summary.arbitration_years) }}
      {{ label_rows('Settlement', summary.settlement_dollars) }}
      {{ label_rows('Subjectively fair', summary.fair) }}
      {{ label_rows('Submitter drafted agreement', summary.drafted) }}
      {{ label_rows('Submitter chose agency', summary.chose_agency) }}
      {{ label_rows('State', summary.statess) }}
    </table>
  </details></div>
  <br>
  {% endfor %}
{% endif %}
{% endblock container %}

templates/splash.jinja.htm
{% extends "base.jinja.htm" %}
{% block title %}arbitration outcomes{% endblock %}
{% block container %}
<div class="jumbotron">
  <h1>⚖️ Arbout</h1>
  <h2>The public record for private settlements</h2>
  <p>Arbout is a crowd-sourced public database of arbitration outcomes. It aggregates search results to preserve the confidentiality of individual cases.</p>
  <p><a class="btn btn-primary" style="font-size: large" href="{{url_for('core.get_submit')}}">📋 Submit a case</a></p>
  <p><a class="btn btn-primary" style="font-size: large" href="{{url_for('core.get_search')}}">🔎 Search our database</a></p>
</div>
<div class="card"><div class="card-body">
  <h3>What is arbitration?</h3>
  <p>Arbitration is an alternative to suing in court.</p>
  <p>Unlike the court system, the arbitration system is run by private companies and doesn't enter its outcomes into the public record. Furthermore, some arbitration is confidential by design, which can shield the parties from the reputational risk of disputes, at the cost of leaving lawmakers and the public in the dark.</p>
  <p>Arbitration is increasingly relevant because many online services include binding arbitration clauses. These clauses can force customers to use arbitration rather than going to court.</p>
</div></div>
<br>
<div class="card"><div class="card-body">
  <h3>How does Arbout work with confidential arbitration?</h3>
  <p>Arbout doesn't reveal the individual contents of any arbitration, and tries to make it difficult to prove that the database contains any individual case. It uses aggregation over search results to only reveal information when many cases have similar outcomes.</p>
  <p>For example, if a company paid a $1000-$1999 settlement in 50 cases, Arbout would reveal that in aggregate. But we wouldn't show the individual amounts or cases.</p>
</div></div>
<br>
<div class="card"><div class="card-body">
  <h3>How do I dispute the information in this database?</h3>
  <p>We have a <a href="{{url_for('core.disputes')}}">dispute process</a>. We're committed to working with arbitration parties and agencies to correct errors.</p>
</div></div>
<br>
<div class="card"><div class="card-body">
  <h3>Who made this and how does it work?</h3>
  <p>Arbout is open source and you can learn about the project's internals and authorship in the <a href="https://github.com/abe-winter/arbout">Arbout github repo</a>.</p>
</div></div>
<br>
<p>©️ 2020 Arbout development team</p>
{% endblock container %}

templates/submit.jinja.htm
{% from 'macros.jinja.htm' import yesno, option_warn, home_link, select_state, select_issue_cat %}
{% extends "base.jinja.htm" %}
{% block title %}submit case{% endblock %}
{% block container %}
{{ home_link() }}
<h1>📋 Submit a case</h1>
<br>
<div class="alert alert-danger">
  <b>Warning</b>: While our system is intended to keep your individual submission confidential, this is a beta product and that confidentiality is subject to technical and legal risks.
  Make sure to read our <a href="{{url_for('core.terms')}}">terms</a>.
</div>
<form method="POST">
  <details class="form-group" open>
    <summary class="h3">Counterparty</summary>
    <div class="form-group"><label>
      <p class="text-muted">Who was the dispute with?</p>
      <input name="counterparty" class="form-control" type="text" required>
    </label></div>
    <div class="form-group"><label>
      Counterparty website (optional)
      <p class="text-muted">We use this to more easily identify companies and group cases.</p>
      <input name="counterparty_domain" class="form-control" type="text">
    </label></div>
    <div class="form-group">
      Are you the claimant?
      {{ yesno('claimant', [('yes', "Yes, I filed the dispute"), ('no', "No, the other party summoned me to arbitration")], True) }}
    </div>
  </details>
  <hr>

  <details class="form-group" open>
    <summary class="h3">Dispute</summary>
    <div class="form-group"><label>
      Issue category
      <p class="text-muted">General type of the dispute. What was wrong with the product or service?</p>
      {{select_issue_cat(categories, required=True)}}
    </label></div>
    <div class="form-group"><label>
      Issue details (optional)
      <p class="text-muted">What was in dispute? Product name, service name, vendor shortcoming. This field is currently not used, but in a future version of Arbout, this will be merged with other similar answers and displayed in search results.</p>
      <input class="form-control" name="issue_det" placeholder="Issue details (optional)">
    </label></div>
    <div class="form-group"><label>
      Terms or contract link (optional)
      <p class="text-muted">Link to the contract or terms of service that governed the deal</p>
      <input class="form-control" name="terms_link" placeholder="Terms or contract link (optional)">
    </label></div>
    <div class="form-group">
      Did you write any of your contract with the counterparty?
      {{ yesno('you_negotiate', [('yes', "Yes"), ('no', "No, they wrote it entirely by themselves")]) }}
    </div>
  </details>
  <hr>

  <details class="form-group" open>
    <summary class="h3">Outcome</summary>
    <div class="form-group"><label>
      How much money did you seek in the settlement? (In dollars)
      <p class="text-muted">Because this amount can be used to identify you individually, we don't publish it in search results unless several other cases have similar amounts. We'll also show statistics about the settlement like percentage rewarded.</p>
      <input class="form-control" name="sought_dollars" type="number">
    </label></div>
    <div class="form-group"><label>
      Actual settlement amount
      <input class="form-control" name="settlement_dollars" type="number">
    </label></div>
    <div class="form-group">
      In your opinion, was the outcome in your favor?
      {{ yesno('favor') }}
    </div>
    <div class="form-group">
      In your opinion, was the arbitration process and outcome fair?
      {{ yesno('fair') }}
    </div>
  </details>
  <hr>

  <details class="form-group" open>
    <summary class="h3">Dates</summary>
    <div class="form-group"><label>
      Month of incident (optional)
      <p class="text-muted">
        Or if it was an ongoing problem, when it started, as best you remember.
        These dates will only be shown in search results in large groups of cases, so your case can't be identified individually.
        We also use these dates to track how long arbitration cases take to process.
      </p>
      <input class="form-control" name="incident_date" type="month">
    </label></div>
    <div class="form-group"><label>
      Month the claimant raised a dispute with the respondent (optional)
      <input class="form-control" name="dispute_date" type="month">
    </label></div>
    <div class="form-group"><label>
      Month arbitration was filed (optional)
      <input class="form-control" name="file_date" type="month">
    </label></div>
    <div class="form-group"><label>
      Month of arbitration
      <input class="form-control" name="arb_date" type="month" required>
    </label></div>
  </details>
  <hr>

  <details class="form-group" open>
    <summary class="h3">Case details</summary>
    <div class="form-group"><label>
      Agency (optional)
      <p class="text-muted">The name of the agency that arbitrated your dispute.</p>
      <input class="form-control" name="agency" placeholder="Agency (optional)">
    </label></div>
    {# todo: autocomplete #}
    <div class="form-group"><label>
      State
      <p class="text-muted">For now, you can only submit cases for US states and territories.</p>
      {{select_state(states)}}
    </label></div>
    <div class="form-group">
      Did you choose the arbitration agency?
      {{ yesno('chose', [('yes', "Yes, I chose it freely"), ('yes_list', "I chose it from a list of options provided by the counterparty"), ('no', "No")]) }}
    </div>
    <div class="form-group"><label>
      Case ID (optional)
      <p class="text-muted">
        The case number or ID that the arbitration agency gave to the case. This won't be published in search results. It will be stored in an encrypted format in our database.
        There's a good reason to give us a case ID: it makes it easier for us to place the burden of proof on the arbitration agency in case of a dispute.
      </p>
      {{ option_warn() }}
      <input class="form-control" name="case_real_id" placeholder="Case ID (optional)">
    </label></div>
  </details>
  <hr>

  <details class="form-group" open>
    <summary class="h3">Your details</summary>
    <div class="form-group"><label>
      Email (optional)
      <p class="text-muted">Give us your email if you want to be contacted in case of a dispute.</p>
      {{ option_warn() }}
      <input class="form-control" name="email" type="email" placeholder="Email (optional)">
    </label></div>
    <div class="form-group"><label>
      Password (optional)
      <p class="text-muted">If you set a password, you'll receive an edit link that allows you to make changes to this page later, or delete it</p>
      <input class="form-control" name="password" type="password" placeholder="Password (optional)">
    </label></div>
  </details>
  <hr>
  <h3>Affirm and submit</h3>
  <p class="text-muted">If you edit this text, your submission will be rejected. If you want to change the terms of the affirmation, please contact us.</p>
  <textarea class="form-control" type="text" name="affirm" rows="8">{{affirmation}}</textarea>
  <br>
  <button role="submit" class="btn btn-primary">Affirm and submit</button>
  <hr>
</form>
{% endblock container %}

templates/terms.jinja.htm
{% from 'macros.jinja.htm' import home_link %}
{% extends "base.jinja.htm" %}
{% block title %}terms and privacy{% endblock %}
{% block container %}
{{ home_link() }}
<h1>Terms of service / privacy notice</h1>
<h3>No legal advice</h3>
<p>Nothing you see on this website or the associated open source accounts or message boards should be construed as legal advice.</p>
<p>It is your responsibility to determine whether the laws and contractual obligations in your particular situation allow you to use this site, whether to submit a case or to search.</p>
<hr>
<h3>Assumption of risk</h3>
<p>As a user, you assume all risk from submitting to this site and from using the search results you find here.</p>
<hr>
<h3>Disputes</h3>
<p>If you think our information is wrong, see <a href="{{url_for('core.disputes')}}">disputes</a>.</p>
<hr>
<h3>Privacy of submissions</h3>
<p>We won't intentionally reveal submissions to a third party unless we are compelled to do so.</p>
<p>If you've given an email address, you may be contacted in case of a dispute of your case. However, we will attempt to place the burden of proof on the disputing party before we contact you. We won't reveal email addresses or other PII to the counterparty unless compelled.</p>
<p><u>A non-exhaustive list of circumstances that could lead to your data being revealed:</u></p>
<ul>
  <li>Certain kinds of repeat searches or statistical attacks may be able to uncover individual cases.</li>
  <li>Our cloud vendor, Google, manages our HTTPS certificates, our hosting cluster, and our database. Notwithstanding internal controls at Google, it would be technically trivial for them to examine the individual cases in our database or our visitor logs. If you don't trust Google, don't use this site.</li>
  <li>We will comply with valid subpoenas or other forms of duress. At our discretion, and depending on the legal resources available to us, we may challenge subpoenas in court or attempt to inform you as soon as possible if your data has been captured by state or other action.</li>
  <li>A failure in our encryption.</li>
  <li>A bug or flaw in our aggregation implementation, or other bugs.</li>
  <li>Other cyberattacks.</li>
  <li>If all of the cases against a party in a given state and year are in the database, the party may infer the presence of an individual case from the revealed total count.</li>
</ul>
<hr>
<h3>Cookies</h3>
<p>We don't intentionally set cookies, and to our knowledge, no site functionality depends on or benefits from cookies. It's possible that our various open source libraries or frameworks automatically set some cookies. It's possible that our cloud vendor or your ISP are setting cookies on the connection.</p>
<hr>
<h3>Cyberattack disclosure policy</h3>
<p>It's our policy to report cyberattacks and data leaks whenever practical. A non-exhaustive list of reasons we may not report an attack immediately or at all:</p>
<ul>
  <li>We are still investigating the attack.</li>
  <li>Disclosing the attack would expose us to legal liability.</li>
  <li>Disclosing the attack would endanger others. For example, the attack was a zero-day and we are working with vendors to mitigate the vulnerability before announcing.</li>
  <li>A law enforcement agency has asked us to postpone announcing while they investigate.</li>
</ul>
<hr>
<h3>Valid version policy</h3>
<p>Most pages on this site have a version tag at the bottom. When this tag corresponds to a version in our public github repository, we guarantee on a best-effort basis that the version of the software serving the site is built from that git verison.</p>
<hr>
{% endblock container %}